# Generated by Django 3.1.4 on 2021-01-05 23:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insira o gênero de um livro (por exemplo, ficção científica)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField(help_text='Insira uma breve descrição do livro', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.autor')),
                ('genero', models.ManyToManyField(help_text='Selecione um gênero para este livro', to='catalogo.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaLivro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID exclusivo para este livro específico em toda a biblioteca', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('M', 'Manutenção'), ('E', 'Por empréstimo'), ('A', 'Acessível'), ('R', 'Reservado')], default='m', help_text='Disponibilidade de livros', max_length=1)),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.livro')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
